resource_types:
- name: pull-request
  type: docker-image
  source:
    repository: jtarchie/pr

resources:
- name: git-clone-resource
  type: git
  source:
    branch: master
    uri: https://github.com/drahnr/oregano.git

- name: git-pull-request-resource
  type: pull-request
  source:
    repo: drahnr/oregano
    access_token: {{github-token}}

- name: oregano-test-fedora
  type: docker-image
  source:
    repository: quay.io/ratpoison/oregano-test-fedora
    username: {{quay-username}}
    password: {{quay-password}}

- name: oregano-test-ubuntu
  type: docker-image
  source:
    repository: quay.io/ratpoison/oregano-test-ubuntu
    username: {{quay-username}}
    password: {{quay-password}}

jobs:
  - name: build-docker-image-fedora
    serial_groups: [network]
    public: true
    plan:
      - get: git-clone-resource
        trigger: true
      - put: oregano-test-fedora
        params:
          cache: true
          tag_as_latest: true
          build: git-clone-resource/.concourse/fedora

  - name: build-docker-image-ubuntu
    serial_groups: [network]
    public: true
    plan:
    - get: git-clone-resource
      trigger: true
    - put: oregano-test-ubuntu
      params:
        cache: true
        tag_as_latest: true
        build: git-clone-resource/.concourse/ubuntu

  - name: compile-pr
    public: true
    plan:
    - aggregate:
      - get: oregano-test-fedora
      - get: git-pull-request-resource
        trigger: true
        serial_groups: [network]
    - task: compile
      image: oregano-test-fedora
      config:
        platform: linux
        inputs:
        - name: git-pull-request-resource
        run:
          path: xvfb-run
          args: ["./waf", "configure", "debug", "--prefix=/tmp", "--notests", "install"]
          dir: "git-pull-request-resource"
      on_success:
        put: git-pull-request-resource
        params:
          path: git-pull-request-resource
          status: success
      on_failure:
        put: git-pull-request-resource
        params:
          path: git-pull-request-resource
          status: failure

  - name: compile
    public: true
    plan:
    - aggregate:
      - get: oregano-test-fedora
      - get: git-clone-resource
        trigger: true
        passed: [build-docker-image-fedora]
    - task: compile
      image: oregano-test-fedora
      config:
        platform: linux
        inputs:
        - name: git-clone-resource
        outputs:
        - name: git-clone-resource-compiled
        run:
          path: xvfb-run
          args: ["./waf", "configure", "debug", "--prefix=/tmp", "install"]
          dir: "git-clone-resource"

  - name: build-pkg-rpm
    public: true
    plan:
    - aggregate:
      - get: oregano-test-fedora
      - get: git-clone-resource
        trigger: true
        passed: [compile, build-docker-image-fedora]
    - task: create-rpm
      image: oregano-test-fedora
      config:
        platform: linux
        inputs:
        - name: git-clone-resource-compiled
        run:
          path: "./.concourse/fedora/buildrpm.sh"
          dir: "git-clone-resource"

  - name: build-pkg-deb
    public: true
    plan:
    - aggregate:
      - get: oregano-test-ubuntu
      - get: git-clone-resource
        trigger: true
        passed: [build-docker-image-ubuntu]
    - task: create-deb
      image: oregano-test-ubuntu
      config:
        platform: linux
        inputs:
        - name: git-clone-resource
        run:
          path: debuild
          args: ["-i", "-us", "-uc", "-b"]
          dir: "git-clone-resource"
