image: oregano-test-fedora:latest
git:
  depth: 1
  path: github.com/drahnr/oregano
script:
  - ./.drone/build.sh
deploy:
  bash:
    script:
      - ./.drone/deploy.sh
notify:
  email:
    recipients:
      - bernhard@beerbach.me
    on_success: false
    on_failure: true
